### ISSUE TITLE
[BUG] Foundry 11 Support

### ISSUE THREAD

**Issue by ascarion** [dmrickey/ckl-advanced-templates-pf1#27]
**Module Version:** v1.4.2

**Describe the bug**
Using measure templates throws an error and nothing happens.

**Screenshots**
Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'getLocalPosition')
[Detected 2 packages: ckl-advanced-templates-pf1, system:pf1]
    at AbilityTemplateCircleGrid.initializePlacement (measured-template-pf-advanced.js:686:36)
    at AbilityTemplateAdvanced.fromData (measured-template-pf-advanced.js:421:32)
    at ActionUse.promptMeasureTemplate (index.js:70:70)
    at async ItemSpellPF.use (item-pf.mjs:1297:23)

**Foundry Version:** 
11

**Game System:** 
PF1

**Comment by dmrickey** [comment]
A large portion of the mod has now been re-written to support foundry v11. Version 2.0.0 was just released.
